"""
Agent 4: Reviewer
Reviews each FAQ item generated by Agent 3 using Gemini.
Checks:
  - Accuracy: Is the answer correct based on the source context?
  - Relevance: Is the question useful and relevant to the document?
  - Clarity: Is the question clear and unambiguous?

Adds review_score (0-10), review_notes, and is_approved to each FAQ item.
Only approved items (score >= 6) pass through.
"""

import logging
import json
import re
import time
from typing import Any

from google import genai

logger = logging.getLogger(__name__)

_APPROVAL_THRESHOLD = 6  # Minimum score to be approved

_SYSTEM_PROMPT = """Bạn là chuyên gia kiểm duyệt nội dung FAQ về Quy Chế Đào Tạo Thạc Sĩ.

Nhiệm vụ: Đánh giá cặp Q&A sau dựa trên context (đoạn văn gốc) được cung cấp.

Tiêu chí chấm điểm (thang 0-10):
- Độ chính xác: Câu trả lời có đúng với văn bản gốc không? (40%)
- Độ liên quan: Câu hỏi có thiết thực và liên quan đến nội dung không? (30%)
- Độ rõ ràng: Câu hỏi và trả lời có dễ hiểu không? (30%)

Trả về JSON hợp lệ (không có markdown):
{
  "score": <số từ 0 đến 10>,
  "notes": "<nhận xét ngắn gọn về chất lượng Q&A, nếu có vấn đề hãy chỉ ra>",
  "approved": <true nếu score >= 6, ngược lại false>
}"""


def run(
    faq_items: list[dict[str, Any]],
    client: genai.Client,
    model_name: str,
) -> list[dict[str, Any]]:
    """
    Review each FAQ item and return only approved ones.

    Args:
        faq_items:  List of FAQ dicts from Agent 3 (FAQ Generator).
        client:     Configured google.genai Client instance.
        model_name: Gemini model name string.

    Returns:
        Filtered list of FAQ items with review metadata added.
    """
    logger.info("[Reviewer] Reviewing %d FAQ items...", len(faq_items))
    reviewed: list[dict[str, Any]] = []
    approved_count = 0

    for i, item in enumerate(faq_items, 1):
        logger.info(
            "[Reviewer] [%d/%d] %s",
            i,
            len(faq_items),
            item.get("question", "")[:70],
        )

        prompt = f"""{_SYSTEM_PROMPT}

---
NGUỒN: {item.get('source', '')}

CÂU HỎI: {item.get('question', '')}

CÂU TRẢ LỜI: {item.get('answer', '')}

CONTEXT GỐC:
{item.get('context', '')}
---

Kết quả review (chỉ JSON):"""

        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
            )
            raw = response.text.strip()
            review = _parse_review_json(raw)
        except Exception as exc:
            logger.warning("[Reviewer] Error reviewing item %s: %s", item["id"], exc)
            review = {"score": 5, "notes": f"Review lỗi: {exc}", "approved": True}

        item = dict(item)
        item["review_score"] = review.get("score", 0)
        item["review_notes"] = review.get("notes", "")
        item["is_approved"] = (
            review.get("approved", False)
            and item["review_score"] >= _APPROVAL_THRESHOLD
        )

        reviewed.append(item)
        if item["is_approved"]:
            approved_count += 1

        time.sleep(0.5)

    # Filter to approved only
    approved = [r for r in reviewed if r["is_approved"]]
    logger.info(
        "[Reviewer] Done. %d/%d items approved.", approved_count, len(faq_items)
    )
    return approved


# ─────────────────────────────────────────────────────────────────────────────

def _parse_review_json(raw: str) -> dict:
    """Parse Gemini's review JSON response."""
    cleaned = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end == -1:
        return {"score": 5, "notes": "Không parse được JSON", "approved": True}
    try:
        return json.loads(cleaned[start : end + 1])
    except json.JSONDecodeError:
        return {"score": 5, "notes": "JSON lỗi", "approved": True}
